### ISSUE TITLE
Complete CB Interferes with UI-Router Transitions

### ISSUE THREAD

**Issue by juddam** [cgwyllie/angular-velocity#18]
*This is probably more a question or enhancement, so apologies in advance if not the right forum*

I'm trying to use angular-velocity + VelocityUI in conjunction with UI-Router to transition views. One thing prohibiting this is how certain transitions apply inline transforms that remain on the element (e.g. slideUpIn leaves `transform: translateY(0px);` after completion).

This results in some undesirable css conflicts, especially when there is a `position: fixed;` element within the transitioned container.

While maybe nuanced, it also seemed like transitioning to a new view with a fixed header/toolbar is a common pattern in app-like projects.

I tried to resolve by setting up a function to simply remove the style attribute on completion, but realized that doing so then prohibited the UI-Router from removing the ui-view from the DOM, which is more problematic.

[Here is a link to demo behaviors](http://codepen.io/juddam/pen/jExvEN/)
*1. Notice that if you remove the transform property, position: fixed works again*
*2. The ui-view element is not removed when calling Velocity complete fn*

Ideally there would be a way to remove inline styles after completion that would not interfere with UI-Router.

```html
<div
	ui-view="main"
	class="velocity-opposites-transition-slideUpIn"
	data-velocity-opts="{duration: 4000, complete: onVelocityComplete($id)}"
	>
</div>
```

```javascript
$scope.onVelocityComplete = function($id) {
    $('[ui-view][data-el-id=' + $id + ']').attr('style', '');
}
```

This is likely more a Velocity / UI-Router conflict, but figured I would start by asking here.

Let me know if I'm missing something or there is another solve.

**Comment by cgwyllie** [comment]
Hi @juddam,

No apologies necessary, this is a perfect forum for discussing such things.

This is actually something that I've been playing with a little recently, and I encountered a similar issue with Velocity leaving inline styles on the element after completion. I solved it the same way you propose, I think there are just a couple of snags in your example.

I think where you are passing the complete function is causing a problem: by specifying `complete: onVelocityComplete($id)`, you're passing the _return value_ of your completion function to Velocity, not a reference to the function itself.

As your complete function returns `undefined`, Velocity/angular-velocity might choke on trying to evaluate it because it will try to 'run' `undefined`. The other issue with this is you will end up removing inline styles at the _start_ of the animation, not the end as intended.

I've made a quick fork of your CodePen (thanks for including one, really useful!) which I think solves your issue: http://codepen.io/anon/pen/azKpve

In this example, the complete function is passed as: `complete: onVelocityComplete`, and the completion handler has been changed to:

```js
  $scope.onCompleteFn = function(el) {
    $(el).attr('style', '')
  }
```

Because this is the Velocity completion callback, it will be passed the element that was animated so you can just go ahead and change its styles :)

Hopefully this is some way to helping resolve the problem! Let me know how this works out for you, or if you have any more general ideas about app view animation features.

Cheers,
Chris

**Comment by juddam** [comment]
:facepalm:

Thanks for the quick reply @cgwyllie -- this completely solves the issue.

Would be interested in checking out best patterns for in app use if you ever post / come across.

Thanks for the great work!

**Comment by cgwyllie** [comment]
No problem @juddam, glad to be of help!

I just released an update in 0.2.4 which might be contributing to the ui-view being left in the DOM as you report. Please feel free to reopen if this is still an issue after updating.

Yeah, I'm hoping to write something up about animating views for apps soon, but I need to also research this more haha..

**Comment by juddam** [comment]
Hey @cgwyllie - did you ever write your method for animating views?

FWIW, I just released a beta of the product I was working on which uses angular-velocity and this completion callback to animate view and modal transitions.

[wayla.com](www.wayla.com)

Method works great, but I still have some improvement to go, especially on mobile, where the frame rate drops causing some jank.

Thought might be interesting if you're still working on this.

**Comment by cgwyllie** [comment]
Hey @juddam, cool! Congrats on launching the project, it's always a good day!

So far I haven't had a chance to write anything or spend more time looking at view animation.

However, some general points that we've noticed working on mobile apps with animation would be:

- Try and minimise watchers in the Angular digest cycle by using [one time binding](http://toddmotto.com/angular-one-time-binding-syntax/)
- Avoid using route resolve blocks if the view being rendered is heavy

The second point seems strange, but what we were observing was that as the view transitioned, it would stutter because the view was being rendered whilst moved. We could reduce this jank by showing a loading spinner/animated icon in the view and doing the data loads in the controller. Because these loads were async, it would allow the view animation to complete before trying to redraw.

I've not dug in to it too deeply though, so these thoughts are just based on 'hunches' and observation, not profiling. I think that the ideal situation would be to load all data necessary to render the view, render it completely with the data, and only _then_ animate the unit as a whole. However, I'm not sure how this would be possible, and again, it's just speculation!

I'll be sure to post again if I can get the time to look deeper into this.

Best of luck with your product!

**Comment by juddam** [comment]
Thanks @cgwyllie -- had forgotten about one time binding.

Yeah, 'view-transitions' were an entirely different beast than 'element-animations'.

Godspeed, and thanks!
